"""
Curated dataset of 110+ travel destinations across the world.

Each destination carries the structured metadata the agentic workflow needs:
    - geography (country, region, continent)
    - best_months: list of months (1-12) the destination is at its best
    - daily_cost_usd: rough on-the-ground cost per person per day
      (lodging + food + local transport + a couple of activities)
    - budget_tier: "budget" | "mid" | "luxury" (derived bucket)
    - flight_band: relative long-haul flight cost band (1 cheap .. 4 pricey)
    - tags: interest tags used for matching
    - blurb: a short human description used to ground the LLM
    - image_query: keyword used by the frontend to fetch a representative photo
"""

from typing import List, Dict


def _tier(daily_cost: int) -> str:
    if daily_cost <= 55:
        return "budget"
    if daily_cost <= 130:
        return "mid"
    return "luxury"


# Months helpers (Northern/Southern hemisphere friendly).
SPRING = [3, 4, 5]
SUMMER = [6, 7, 8]
AUTUMN = [9, 10, 11]
WINTER = [12, 1, 2]


_RAW: List[Dict] = [
    # ---------------------- ASIA ----------------------
    {"name": "Bali", "country": "Indonesia", "region": "Southeast Asia", "continent": "Asia",
     "best_months": [4, 5, 6, 7, 8, 9], "daily_cost_usd": 45, "flight_band": 3,
     "tags": ["beach", "nature", "culture", "romance", "wellness", "adventure"],
     "blurb": "Lush rice terraces, surf breaks and temple-dotted hills with a famously low cost of living.",
     "image_query": "bali rice terrace temple"},
    {"name": "Bangkok", "country": "Thailand", "region": "Southeast Asia", "continent": "Asia",
     "best_months": [11, 12, 1, 2], "daily_cost_usd": 40, "flight_band": 3,
     "tags": ["food", "nightlife", "culture", "city", "history", "budget"],
     "blurb": "Frenetic street-food capital with glittering temples and rooftop bars.",
     "image_query": "bangkok temple skyline"},
    {"name": "Chiang Mai", "country": "Thailand", "region": "Southeast Asia", "continent": "Asia",
     "best_months": [11, 12, 1, 2], "daily_cost_usd": 32, "flight_band": 3,
     "tags": ["culture", "nature", "food", "wellness", "budget", "adventure"],
     "blurb": "Mountain-ringed old city of temples, night markets and elephant sanctuaries.",
     "image_query": "chiang mai temple lantern"},
    {"name": "Phuket", "country": "Thailand", "region": "Southeast Asia", "continent": "Asia",
     "best_months": [11, 12, 1, 2, 3], "daily_cost_usd": 55, "flight_band": 3,
     "tags": ["beach", "nightlife", "family", "romance", "water sports"],
     "blurb": "Thailand's largest island, fringed by Andaman Sea beaches and limestone bays.",
     "image_query": "phuket beach island"},
    {"name": "Hanoi", "country": "Vietnam", "region": "Southeast Asia", "continent": "Asia",
     "best_months": [10, 11, 3, 4], "daily_cost_usd": 30, "flight_band": 3,
     "tags": ["food", "culture", "history", "city", "budget"],
     "blurb": "Atmospheric old-quarter chaos, lakeside calm and legendary street pho.",
     "image_query": "hanoi old quarter street"},
    {"name": "Ha Long Bay", "country": "Vietnam", "region": "Southeast Asia", "continent": "Asia",
     "best_months": [10, 11, 3, 4], "daily_cost_usd": 60, "flight_band": 3,
     "tags": ["nature", "romance", "cruise", "adventure"],
     "blurb": "Emerald waters studded with thousands of limestone karst islands.",
     "image_query": "ha long bay karst boat"},
    {"name": "Siem Reap", "country": "Cambodia", "region": "Southeast Asia", "continent": "Asia",
     "best_months": [11, 12, 1, 2], "daily_cost_usd": 30, "flight_band": 3,
     "tags": ["history", "culture", "budget", "adventure"],
     "blurb": "Gateway to the sprawling temple complex of Angkor Wat at sunrise.",
     "image_query": "angkor wat sunrise"},
    {"name": "Singapore", "country": "Singapore", "region": "Southeast Asia", "continent": "Asia",
     "best_months": [2, 3, 4, 7, 8], "daily_cost_usd": 140, "flight_band": 3,
     "tags": ["city", "food", "family", "luxury", "shopping", "nightlife"],
     "blurb": "Hyper-modern garden city of hawker food, futuristic gardens and rooftop pools.",
     "image_query": "singapore marina bay gardens"},
    {"name": "Kuala Lumpur", "country": "Malaysia", "region": "Southeast Asia", "continent": "Asia",
     "best_months": [5, 6, 7, 12, 1], "daily_cost_usd": 45, "flight_band": 3,
     "tags": ["city", "food", "shopping", "culture", "budget"],
     "blurb": "Twin-tower skyline above a melting pot of Malay, Chinese and Indian flavours.",
     "image_query": "kuala lumpur petronas towers"},
    {"name": "Tokyo", "country": "Japan", "region": "East Asia", "continent": "Asia",
     "best_months": [3, 4, 10, 11], "daily_cost_usd": 130, "flight_band": 4,
     "tags": ["city", "food", "culture", "shopping", "nightlife", "technology"],
     "blurb": "Neon-lit megacity where ancient shrines sit beside robot cafes and Michelin ramen.",
     "image_query": "tokyo shibuya night"},
    {"name": "Kyoto", "country": "Japan", "region": "East Asia", "continent": "Asia",
     "best_months": [3, 4, 11], "daily_cost_usd": 120, "flight_band": 4,
     "tags": ["culture", "history", "romance", "nature", "food"],
     "blurb": "Japan's old capital of golden pavilions, geisha lanes and bamboo groves.",
     "image_query": "kyoto torii gate autumn"},
    {"name": "Seoul", "country": "South Korea", "region": "East Asia", "continent": "Asia",
     "best_months": [4, 5, 9, 10], "daily_cost_usd": 95, "flight_band": 4,
     "tags": ["city", "food", "shopping", "nightlife", "culture", "technology"],
     "blurb": "K-pop energy, palace courtyards and 24-hour street-food alleys.",
     "image_query": "seoul palace skyline"},
    {"name": "Hong Kong", "country": "Hong Kong", "region": "East Asia", "continent": "Asia",
     "best_months": [10, 11, 12], "daily_cost_usd": 120, "flight_band": 4,
     "tags": ["city", "food", "shopping", "nightlife", "skyline"],
     "blurb": "Vertiginous skyline, dim sum institutions and a peak-top harbour view.",
     "image_query": "hong kong skyline victoria peak"},
    {"name": "Beijing", "country": "China", "region": "East Asia", "continent": "Asia",
     "best_months": [4, 5, 9, 10], "daily_cost_usd": 70, "flight_band": 4,
     "tags": ["history", "culture", "city", "food"],
     "blurb": "Imperial palaces, hutong alleys and a wild stretch of the Great Wall.",
     "image_query": "great wall of china"},
    {"name": "Jaipur", "country": "India", "region": "South Asia", "continent": "Asia",
     "best_months": [10, 11, 12, 1, 2], "daily_cost_usd": 28, "flight_band": 0,
     "tags": ["history", "culture", "budget", "romance", "shopping"],
     "blurb": "The Pink City of hilltop forts, mirrored palaces and bazaar colour.",
     "image_query": "jaipur hawa mahal palace"},
    {"name": "Goa", "country": "India", "region": "South Asia", "continent": "Asia",
     "best_months": [11, 12, 1, 2], "daily_cost_usd": 30, "flight_band": 0,
     "tags": ["beach", "nightlife", "budget", "relaxation", "water sports"],
     "blurb": "Palm-backed Arabian Sea beaches with shack food and Portuguese-era churches.",
     "image_query": "goa beach palm sunset"},
    {"name": "Kerala Backwaters", "country": "India", "region": "South Asia", "continent": "Asia",
     "best_months": [9, 10, 11, 12, 1, 2], "daily_cost_usd": 35, "flight_band": 0,
     "tags": ["nature", "romance", "wellness", "budget", "cruise"],
     "blurb": "Houseboats drifting through palm-lined canals and tea-green hills.",
     "image_query": "kerala backwaters houseboat"},
    # ---------------------- INDIA (domestic, budget-friendly) ----------------------
    {"name": "Rishikesh", "country": "India", "region": "South Asia", "continent": "Asia",
     "best_months": [2, 3, 4, 9, 10, 11], "daily_cost_usd": 18, "flight_band": 0,
     "tags": ["adventure", "wellness", "spiritual", "nature", "budget", "trekking"],
     "blurb": "Yoga capital on the Ganges with river rafting, ashrams and Himalayan foothills.",
     "image_query": "rishikesh ganges river bridge"},
    {"name": "Manali", "country": "India", "region": "South Asia", "continent": "Asia",
     "best_months": [3, 4, 5, 6, 10], "daily_cost_usd": 22, "flight_band": 0,
     "tags": ["mountains", "adventure", "nature", "romance", "budget", "trekking"],
     "blurb": "Snow-dusted Himalayan valley town of pine forests, hot springs and high passes.",
     "image_query": "manali himalayas snow valley"},
    {"name": "Udaipur", "country": "India", "region": "South Asia", "continent": "Asia",
     "best_months": [9, 10, 11, 12, 1, 2], "daily_cost_usd": 30, "flight_band": 0,
     "tags": ["romance", "culture", "history", "city", "budget"],
     "blurb": "The lake city of marble palaces, sunset boat rides and old-world royalty.",
     "image_query": "udaipur lake palace sunset"},
    {"name": "Varanasi", "country": "India", "region": "South Asia", "continent": "Asia",
     "best_months": [10, 11, 12, 1, 2, 3], "daily_cost_usd": 16, "flight_band": 0,
     "tags": ["spiritual", "culture", "history", "budget"],
     "blurb": "India's holiest city of ghats, dawn river rituals and labyrinthine lanes.",
     "image_query": "varanasi ghats ganges boats"},
    {"name": "Agra", "country": "India", "region": "South Asia", "continent": "Asia",
     "best_months": [10, 11, 12, 1, 2], "daily_cost_usd": 22, "flight_band": 0,
     "tags": ["history", "culture", "romance", "budget"],
     "blurb": "Home of the Taj Mahal, Mughal forts and marble inlay craft.",
     "image_query": "taj mahal agra sunrise"},
    {"name": "Munnar", "country": "India", "region": "South Asia", "continent": "Asia",
     "best_months": [9, 10, 11, 12, 1, 2, 3], "daily_cost_usd": 24, "flight_band": 0,
     "tags": ["nature", "mountains", "romance", "wellness", "budget"],
     "blurb": "Rolling emerald tea plantations and misty hills in Kerala's Western Ghats.",
     "image_query": "munnar tea plantation hills"},
    {"name": "Hampi", "country": "India", "region": "South Asia", "continent": "Asia",
     "best_months": [10, 11, 12, 1, 2], "daily_cost_usd": 16, "flight_band": 0,
     "tags": ["history", "culture", "adventure", "budget", "nature"],
     "blurb": "Surreal boulder-strewn landscape scattered with ancient Vijayanagara ruins.",
     "image_query": "hampi boulders temple ruins"},
    {"name": "Pondicherry", "country": "India", "region": "South Asia", "continent": "Asia",
     "best_months": [10, 11, 12, 1, 2], "daily_cost_usd": 26, "flight_band": 0,
     "tags": ["beach", "relaxation", "culture", "romance", "food", "budget"],
     "blurb": "Breezy French-quarter cafes, seaside promenades and Auroville calm.",
     "image_query": "pondicherry french colony street"},
    {"name": "Leh Ladakh", "country": "India", "region": "South Asia", "continent": "Asia",
     "best_months": [6, 7, 8, 9], "daily_cost_usd": 30, "flight_band": 0,
     "tags": ["mountains", "adventure", "nature", "trekking", "budget"],
     "blurb": "High-desert moonscape of turquoise lakes, monasteries and 5,000m passes.",
     "image_query": "leh ladakh pangong lake mountains"},
    {"name": "Darjeeling", "country": "India", "region": "South Asia", "continent": "Asia",
     "best_months": [3, 4, 5, 10, 11], "daily_cost_usd": 22, "flight_band": 0,
     "tags": ["mountains", "nature", "romance", "budget", "wellness"],
     "blurb": "Tea-terraced Himalayan hill station with toy trains and Kanchenjunga views.",
     "image_query": "darjeeling tea garden himalaya"},
    {"name": "Jaisalmer", "country": "India", "region": "South Asia", "continent": "Asia",
     "best_months": [10, 11, 12, 1, 2], "daily_cost_usd": 24, "flight_band": 0,
     "tags": ["history", "adventure", "culture", "romance", "budget"],
     "blurb": "Golden sandstone desert fort with camel safaris and Thar dune camps.",
     "image_query": "jaisalmer golden fort desert"},
    {"name": "Andaman Islands", "country": "India", "region": "South Asia", "continent": "Asia",
     "best_months": [11, 12, 1, 2, 3, 4], "daily_cost_usd": 40, "flight_band": 1,
     "tags": ["beach", "nature", "water sports", "romance", "relaxation"],
     "blurb": "Powder-white sands and coral reefs in the turquoise Bay of Bengal.",
     "image_query": "andaman havelock beach turquoise"},
    {"name": "Maldives", "country": "Maldives", "region": "South Asia", "continent": "Asia",
     "best_months": [11, 12, 1, 2, 3, 4], "daily_cost_usd": 320, "flight_band": 4,
     "tags": ["beach", "luxury", "romance", "honeymoon", "diving", "wellness"],
     "blurb": "Overwater villas above impossibly clear lagoons and coral reefs.",
     "image_query": "maldives overwater villa lagoon"},
    {"name": "Colombo & South Coast", "country": "Sri Lanka", "region": "South Asia", "continent": "Asia",
     "best_months": [12, 1, 2, 3], "daily_cost_usd": 40, "flight_band": 3,
     "tags": ["beach", "culture", "nature", "budget", "adventure"],
     "blurb": "Tea country, ancient stupas and surf beaches on a compact tropical island.",
     "image_query": "sri lanka beach train"},
    {"name": "Kathmandu & Pokhara", "country": "Nepal", "region": "South Asia", "continent": "Asia",
     "best_months": [10, 11, 3, 4], "daily_cost_usd": 30, "flight_band": 3,
     "tags": ["adventure", "mountains", "culture", "budget", "trekking", "nature"],
     "blurb": "Himalayan trailheads, prayer-flag temples and lakeside calm below the Annapurnas.",
     "image_query": "nepal himalaya prayer flags"},
    {"name": "Dubai", "country": "UAE", "region": "Middle East", "continent": "Asia",
     "best_months": [11, 12, 1, 2, 3], "daily_cost_usd": 160, "flight_band": 3,
     "tags": ["luxury", "city", "shopping", "family", "desert", "skyline"],
     "blurb": "Record-breaking towers, desert safaris and gold-souk glamour.",
     "image_query": "dubai burj khalifa skyline"},
    {"name": "Petra & Wadi Rum", "country": "Jordan", "region": "Middle East", "continent": "Asia",
     "best_months": [3, 4, 5, 10, 11], "daily_cost_usd": 75, "flight_band": 3,
     "tags": ["history", "adventure", "desert", "culture", "nature"],
     "blurb": "A rose-red city carved into cliffs and the Mars-like sands of Wadi Rum.",
     "image_query": "petra treasury jordan"},
    {"name": "Istanbul", "country": "Turkey", "region": "Middle East", "continent": "Asia",
     "best_months": [4, 5, 9, 10], "daily_cost_usd": 55, "flight_band": 2,
     "tags": ["history", "culture", "food", "city", "romance"],
     "blurb": "Where Europe meets Asia: domes, bazaars and Bosphorus ferries.",
     "image_query": "istanbul hagia sophia bosphorus"},
    {"name": "Cappadocia", "country": "Turkey", "region": "Middle East", "continent": "Asia",
     "best_months": [4, 5, 6, 9, 10], "daily_cost_usd": 60, "flight_band": 2,
     "tags": ["adventure", "romance", "nature", "history", "honeymoon"],
     "blurb": "Fairy-chimney valleys best seen at dawn from a hot-air balloon.",
     "image_query": "cappadocia hot air balloon"},

    # ---------------------- EUROPE ----------------------
    {"name": "Paris", "country": "France", "region": "Western Europe", "continent": "Europe",
     "best_months": [4, 5, 6, 9, 10], "daily_cost_usd": 150, "flight_band": 2,
     "tags": ["romance", "city", "food", "culture", "art", "shopping"],
     "blurb": "The eternal city of light: cafe terraces, the Louvre and the Eiffel sparkle.",
     "image_query": "paris eiffel tower street"},
    {"name": "Nice & French Riviera", "country": "France", "region": "Western Europe", "continent": "Europe",
     "best_months": [5, 6, 9], "daily_cost_usd": 140, "flight_band": 2,
     "tags": ["beach", "luxury", "romance", "food", "relaxation"],
     "blurb": "Azure-coast promenades, sun-baked old towns and glamorous harbours.",
     "image_query": "french riviera nice coast"},
    {"name": "Rome", "country": "Italy", "region": "Southern Europe", "continent": "Europe",
     "best_months": [4, 5, 9, 10], "daily_cost_usd": 120, "flight_band": 2,
     "tags": ["history", "culture", "food", "city", "art", "romance"],
     "blurb": "An open-air museum of ruins, Renaissance squares and perfect pasta.",
     "image_query": "rome colosseum"},
    {"name": "Venice", "country": "Italy", "region": "Southern Europe", "continent": "Europe",
     "best_months": [4, 5, 9, 10], "daily_cost_usd": 135, "flight_band": 2,
     "tags": ["romance", "history", "art", "honeymoon", "culture"],
     "blurb": "Canal-laced city of gondolas, masked carnival and golden basilicas.",
     "image_query": "venice grand canal gondola"},
    {"name": "Amalfi Coast", "country": "Italy", "region": "Southern Europe", "continent": "Europe",
     "best_months": [5, 6, 9], "daily_cost_usd": 160, "flight_band": 2,
     "tags": ["beach", "romance", "luxury", "food", "honeymoon"],
     "blurb": "Pastel villages clinging to cliffs above the Tyrrhenian Sea.",
     "image_query": "amalfi coast positano"},
    {"name": "Florence & Tuscany", "country": "Italy", "region": "Southern Europe", "continent": "Europe",
     "best_months": [5, 6, 9, 10], "daily_cost_usd": 125, "flight_band": 2,
     "tags": ["art", "history", "food", "romance", "culture", "wine"],
     "blurb": "Renaissance masterpieces in town and rolling vineyard hills beyond.",
     "image_query": "tuscany florence vineyard"},
    {"name": "Barcelona", "country": "Spain", "region": "Southern Europe", "continent": "Europe",
     "best_months": [5, 6, 9, 10], "daily_cost_usd": 110, "flight_band": 2,
     "tags": ["city", "beach", "food", "art", "nightlife", "culture"],
     "blurb": "Gaudi's surreal architecture, tapas bars and Mediterranean beaches.",
     "image_query": "barcelona sagrada familia"},
    {"name": "Madrid", "country": "Spain", "region": "Southern Europe", "continent": "Europe",
     "best_months": [4, 5, 9, 10], "daily_cost_usd": 95, "flight_band": 2,
     "tags": ["city", "food", "art", "nightlife", "culture"],
     "blurb": "Grand boulevards, world-class galleries and late-night tapas crawls.",
     "image_query": "madrid plaza mayor"},
    {"name": "Seville", "country": "Spain", "region": "Southern Europe", "continent": "Europe",
     "best_months": [3, 4, 5, 10], "daily_cost_usd": 85, "flight_band": 2,
     "tags": ["culture", "history", "romance", "food", "flamenco"],
     "blurb": "Moorish palaces, orange-scented plazas and flamenco's beating heart.",
     "image_query": "seville plaza espana"},
    {"name": "Lisbon", "country": "Portugal", "region": "Southern Europe", "continent": "Europe",
     "best_months": [4, 5, 6, 9, 10], "daily_cost_usd": 80, "flight_band": 2,
     "tags": ["city", "food", "culture", "romance", "budget", "beach"],
     "blurb": "Hilly tram rides, tile-clad facades and custard tarts by the Atlantic.",
     "image_query": "lisbon tram yellow"},
    {"name": "Porto", "country": "Portugal", "region": "Southern Europe", "continent": "Europe",
     "best_months": [5, 6, 9, 10], "daily_cost_usd": 70, "flight_band": 2,
     "tags": ["food", "wine", "culture", "romance", "budget"],
     "blurb": "Port-wine cellars, riverside tiles and one of Europe's great bridges.",
     "image_query": "porto douro river bridge"},
    {"name": "Santorini", "country": "Greece", "region": "Southern Europe", "continent": "Europe",
     "best_months": [5, 6, 9, 10], "daily_cost_usd": 150, "flight_band": 2,
     "tags": ["romance", "beach", "luxury", "honeymoon", "relaxation"],
     "blurb": "Whitewashed cliffside villages above a flooded volcanic caldera.",
     "image_query": "santorini blue dome sunset"},
    {"name": "Athens", "country": "Greece", "region": "Southern Europe", "continent": "Europe",
     "best_months": [4, 5, 9, 10], "daily_cost_usd": 85, "flight_band": 2,
     "tags": ["history", "culture", "food", "city"],
     "blurb": "The Acropolis crowning a buzzing, sun-drenched ancient capital.",
     "image_query": "athens acropolis parthenon"},
    {"name": "Crete", "country": "Greece", "region": "Southern Europe", "continent": "Europe",
     "best_months": [5, 6, 9, 10], "daily_cost_usd": 90, "flight_band": 2,
     "tags": ["beach", "history", "food", "nature", "family"],
     "blurb": "Greece's largest island: pink-sand coves, gorges and Minoan ruins.",
     "image_query": "crete beach balos"},
    {"name": "London", "country": "United Kingdom", "region": "Western Europe", "continent": "Europe",
     "best_months": [5, 6, 7, 9], "daily_cost_usd": 170, "flight_band": 2,
     "tags": ["city", "history", "culture", "art", "shopping", "family"],
     "blurb": "Royal pageantry, world museums and a restless creative pulse.",
     "image_query": "london big ben thames"},
    {"name": "Edinburgh", "country": "United Kingdom", "region": "Western Europe", "continent": "Europe",
     "best_months": [5, 6, 7, 8], "daily_cost_usd": 120, "flight_band": 2,
     "tags": ["history", "culture", "city", "romance"],
     "blurb": "A medieval castle above festival streets and misty Highland gateways.",
     "image_query": "edinburgh castle old town"},
    {"name": "Amsterdam", "country": "Netherlands", "region": "Western Europe", "continent": "Europe",
     "best_months": [4, 5, 6, 9], "daily_cost_usd": 130, "flight_band": 2,
     "tags": ["city", "culture", "art", "nightlife", "cycling"],
     "blurb": "Gabled canal houses, masterpiece galleries and bicycle-bell streets.",
     "image_query": "amsterdam canal houses"},
    {"name": "Berlin", "country": "Germany", "region": "Central Europe", "continent": "Europe",
     "best_months": [5, 6, 7, 9], "daily_cost_usd": 100, "flight_band": 2,
     "tags": ["city", "history", "nightlife", "art", "culture"],
     "blurb": "Cold-war history, edgy art and a legendary after-dark scene.",
     "image_query": "berlin brandenburg gate"},
    {"name": "Munich & Bavaria", "country": "Germany", "region": "Central Europe", "continent": "Europe",
     "best_months": [5, 6, 7, 9], "daily_cost_usd": 115, "flight_band": 2,
     "tags": ["culture", "history", "family", "mountains", "beer"],
     "blurb": "Beer-hall cheer, fairytale castles and Alpine day trips.",
     "image_query": "neuschwanstein castle bavaria"},
    {"name": "Prague", "country": "Czechia", "region": "Central Europe", "continent": "Europe",
     "best_months": [4, 5, 6, 9], "daily_cost_usd": 70, "flight_band": 2,
     "tags": ["history", "romance", "culture", "city", "budget", "beer"],
     "blurb": "A storybook old town of spires, a castle and a 600-year-old bridge.",
     "image_query": "prague charles bridge castle"},
    {"name": "Vienna", "country": "Austria", "region": "Central Europe", "continent": "Europe",
     "best_months": [4, 5, 6, 9], "daily_cost_usd": 110, "flight_band": 2,
     "tags": ["culture", "history", "art", "romance", "music"],
     "blurb": "Imperial palaces, coffee-house culture and concert-hall grandeur.",
     "image_query": "vienna schonbrunn palace"},
    {"name": "Hallstatt & Salzburg", "country": "Austria", "region": "Central Europe", "continent": "Europe",
     "best_months": [5, 6, 9], "daily_cost_usd": 120, "flight_band": 2,
     "tags": ["nature", "romance", "mountains", "culture"],
     "blurb": "Lakeside Alpine villages straight out of a postcard.",
     "image_query": "hallstatt austria lake"},
    {"name": "Swiss Alps (Interlaken)", "country": "Switzerland", "region": "Central Europe", "continent": "Europe",
     "best_months": [6, 7, 8, 12, 1, 2], "daily_cost_usd": 220, "flight_band": 2,
     "tags": ["mountains", "adventure", "nature", "luxury", "skiing", "honeymoon"],
     "blurb": "Snow-capped peaks, paragliding valleys and scenic mountain railways.",
     "image_query": "swiss alps interlaken jungfrau"},
    {"name": "Zurich", "country": "Switzerland", "region": "Central Europe", "continent": "Europe",
     "best_months": [5, 6, 7, 9], "daily_cost_usd": 200, "flight_band": 2,
     "tags": ["city", "luxury", "nature", "culture"],
     "blurb": "Lakeside elegance, alpine views and a polished old town.",
     "image_query": "zurich lake old town"},
    {"name": "Reykjavik & Ring Road", "country": "Iceland", "region": "Northern Europe", "continent": "Europe",
     "best_months": [6, 7, 8, 9], "daily_cost_usd": 190, "flight_band": 2,
     "tags": ["nature", "adventure", "northern lights", "road trip"],
     "blurb": "Waterfalls, geysers, black-sand beaches and aurora-lit winter skies.",
     "image_query": "iceland waterfall aurora"},
    {"name": "Norwegian Fjords (Bergen)", "country": "Norway", "region": "Northern Europe", "continent": "Europe",
     "best_months": [6, 7, 8], "daily_cost_usd": 180, "flight_band": 2,
     "tags": ["nature", "adventure", "cruise", "mountains", "road trip"],
     "blurb": "Deep glacial fjords, wooden wharf towns and midnight-sun hikes.",
     "image_query": "norway fjord bergen"},
    {"name": "Tromso", "country": "Norway", "region": "Northern Europe", "continent": "Europe",
     "best_months": [11, 12, 1, 2, 3], "daily_cost_usd": 185, "flight_band": 2,
     "tags": ["northern lights", "adventure", "nature", "winter"],
     "blurb": "Arctic base camp for aurora hunting, dog-sledding and whale watching.",
     "image_query": "tromso northern lights"},
    {"name": "Copenhagen", "country": "Denmark", "region": "Northern Europe", "continent": "Europe",
     "best_months": [5, 6, 7, 8], "daily_cost_usd": 150, "flight_band": 2,
     "tags": ["city", "food", "design", "cycling", "culture"],
     "blurb": "Hygge harbours, New Nordic kitchens and bike-friendly canals.",
     "image_query": "copenhagen nyhavn harbour"},
    {"name": "Stockholm", "country": "Sweden", "region": "Northern Europe", "continent": "Europe",
     "best_months": [6, 7, 8], "daily_cost_usd": 145, "flight_band": 2,
     "tags": ["city", "design", "nature", "culture"],
     "blurb": "A 14-island capital of old-town lanes, design and archipelago ferries.",
     "image_query": "stockholm gamla stan"},
    {"name": "Dubrovnik", "country": "Croatia", "region": "Southern Europe", "continent": "Europe",
     "best_months": [5, 6, 9, 10], "daily_cost_usd": 100, "flight_band": 2,
     "tags": ["history", "beach", "romance", "culture"],
     "blurb": "A walled Adriatic old town of marble streets and sea-cliff swims.",
     "image_query": "dubrovnik city walls adriatic"},
    {"name": "Split & Dalmatian Coast", "country": "Croatia", "region": "Southern Europe", "continent": "Europe",
     "best_months": [5, 6, 9], "daily_cost_usd": 90, "flight_band": 2,
     "tags": ["beach", "history", "island hopping", "nightlife"],
     "blurb": "A Roman palace turned living city, gateway to turquoise island hops.",
     "image_query": "split croatia coast"},
    {"name": "Budapest", "country": "Hungary", "region": "Central Europe", "continent": "Europe",
     "best_months": [4, 5, 6, 9], "daily_cost_usd": 65, "flight_band": 2,
     "tags": ["history", "culture", "budget", "romance", "thermal baths", "nightlife"],
     "blurb": "Grand riverside parliament, ruin bars and steaming thermal baths.",
     "image_query": "budapest parliament danube"},
    {"name": "Krakow", "country": "Poland", "region": "Central Europe", "continent": "Europe",
     "best_months": [5, 6, 9], "daily_cost_usd": 55, "flight_band": 2,
     "tags": ["history", "culture", "budget", "city"],
     "blurb": "A perfectly preserved medieval square with sobering 20th-century history nearby.",
     "image_query": "krakow market square"},

    # ---------------------- AFRICA ----------------------
    {"name": "Marrakech", "country": "Morocco", "region": "North Africa", "continent": "Africa",
     "best_months": [3, 4, 5, 10, 11], "daily_cost_usd": 50, "flight_band": 2,
     "tags": ["culture", "history", "food", "shopping", "budget", "desert"],
     "blurb": "Labyrinthine souks, riad courtyards and a snake-charming main square.",
     "image_query": "marrakech medina souk"},
    {"name": "Cape Town", "country": "South Africa", "region": "Southern Africa", "continent": "Africa",
     "best_months": [11, 12, 1, 2, 3], "daily_cost_usd": 75, "flight_band": 4,
     "tags": ["nature", "beach", "adventure", "food", "wine", "city"],
     "blurb": "Table Mountain over Atlantic beaches, penguins and winelands.",
     "image_query": "cape town table mountain"},
    {"name": "Serengeti & Ngorongoro", "country": "Tanzania", "region": "East Africa", "continent": "Africa",
     "best_months": [6, 7, 8, 9, 10], "daily_cost_usd": 280, "flight_band": 4,
     "tags": ["safari", "wildlife", "nature", "adventure", "luxury"],
     "blurb": "The Great Migration thundering across endless golden plains.",
     "image_query": "serengeti safari wildebeest"},
    {"name": "Maasai Mara", "country": "Kenya", "region": "East Africa", "continent": "Africa",
     "best_months": [7, 8, 9, 10], "daily_cost_usd": 250, "flight_band": 4,
     "tags": ["safari", "wildlife", "nature", "adventure", "luxury"],
     "blurb": "Big-cat country and river crossings at the heart of the migration.",
     "image_query": "maasai mara lion safari"},
    {"name": "Zanzibar", "country": "Tanzania", "region": "East Africa", "continent": "Africa",
     "best_months": [6, 7, 8, 9, 10], "daily_cost_usd": 70, "flight_band": 4,
     "tags": ["beach", "romance", "culture", "diving", "honeymoon"],
     "blurb": "Spice-island white sands, dhow sails and a Swahili stone town.",
     "image_query": "zanzibar beach dhow"},
    {"name": "Victoria Falls", "country": "Zimbabwe", "region": "Southern Africa", "continent": "Africa",
     "best_months": [6, 7, 8, 9], "daily_cost_usd": 120, "flight_band": 4,
     "tags": ["nature", "adventure", "wildlife"],
     "blurb": "The thundering 'smoke that thunders' on the Zambezi.",
     "image_query": "victoria falls zambezi"},
    {"name": "Cairo & the Pyramids", "country": "Egypt", "region": "North Africa", "continent": "Africa",
     "best_months": [10, 11, 12, 1, 2, 3], "daily_cost_usd": 45, "flight_band": 3,
     "tags": ["history", "culture", "budget", "adventure"],
     "blurb": "The last ancient wonder beside a chaotic, deep-rooted megacity.",
     "image_query": "giza pyramids sphinx"},
    {"name": "Chefchaouen", "country": "Morocco", "region": "North Africa", "continent": "Africa",
     "best_months": [4, 5, 9, 10], "daily_cost_usd": 40, "flight_band": 2,
     "tags": ["culture", "budget", "romance", "photography"],
     "blurb": "The blue-washed mountain town of dreamy cobalt alleys.",
     "image_query": "chefchaouen blue city"},
    {"name": "Seychelles", "country": "Seychelles", "region": "East Africa", "continent": "Africa",
     "best_months": [4, 5, 10, 11], "daily_cost_usd": 250, "flight_band": 4,
     "tags": ["beach", "luxury", "romance", "honeymoon", "diving"],
     "blurb": "Granite-boulder beaches and rare palm forests in the Indian Ocean.",
     "image_query": "seychelles beach granite boulder"},
    {"name": "Mauritius", "country": "Mauritius", "region": "East Africa", "continent": "Africa",
     "best_months": [5, 6, 9, 10, 11], "daily_cost_usd": 130, "flight_band": 4,
     "tags": ["beach", "luxury", "family", "honeymoon", "water sports"],
     "blurb": "Lagoon resorts, sugar-cane hills and rum-distillery afternoons.",
     "image_query": "mauritius lagoon beach"},

    # ---------------------- NORTH AMERICA ----------------------
    {"name": "New York City", "country": "United States", "region": "USA East", "continent": "North America",
     "best_months": [5, 6, 9, 10, 12], "daily_cost_usd": 200, "flight_band": 2,
     "tags": ["city", "food", "art", "shopping", "nightlife", "culture"],
     "blurb": "The city that never sleeps: skyline icons, Broadway and global eats.",
     "image_query": "new york city skyline"},
    {"name": "San Francisco", "country": "United States", "region": "USA West", "continent": "North America",
     "best_months": [9, 10, 5, 6], "daily_cost_usd": 190, "flight_band": 2,
     "tags": ["city", "food", "nature", "technology", "culture"],
     "blurb": "Fog-wrapped bridges, cable cars and bay-side neighbourhoods.",
     "image_query": "san francisco golden gate"},
    {"name": "Las Vegas", "country": "United States", "region": "USA West", "continent": "North America",
     "best_months": [3, 4, 5, 10, 11], "daily_cost_usd": 150, "flight_band": 2,
     "tags": ["nightlife", "city", "family", "entertainment"],
     "blurb": "Neon casinos, mega-shows and a desert-canyon backyard.",
     "image_query": "las vegas strip neon"},
    {"name": "Grand Canyon & Utah Parks", "country": "United States", "region": "USA West", "continent": "North America",
     "best_months": [4, 5, 9, 10], "daily_cost_usd": 110, "flight_band": 2,
     "tags": ["nature", "adventure", "road trip", "hiking", "family"],
     "blurb": "Mile-deep canyons and red-rock arches on an epic Southwest loop.",
     "image_query": "grand canyon sunrise"},
    {"name": "Hawaii (Maui)", "country": "United States", "region": "Pacific", "continent": "North America",
     "best_months": [4, 5, 9, 10], "daily_cost_usd": 230, "flight_band": 3,
     "tags": ["beach", "nature", "luxury", "romance", "honeymoon", "adventure"],
     "blurb": "Volcanic sunrises, waterfall drives and turquoise snorkel coves.",
     "image_query": "maui hawaii beach"},
    {"name": "Miami", "country": "United States", "region": "USA East", "continent": "North America",
     "best_months": [11, 12, 1, 2, 3, 4], "daily_cost_usd": 170, "flight_band": 2,
     "tags": ["beach", "nightlife", "city", "luxury"],
     "blurb": "Art-deco beachfront, Latin rhythm and turquoise Atlantic days.",
     "image_query": "miami beach art deco"},
    {"name": "New Orleans", "country": "United States", "region": "USA South", "continent": "North America",
     "best_months": [2, 3, 4, 10, 11], "daily_cost_usd": 130, "flight_band": 2,
     "tags": ["food", "music", "culture", "nightlife", "history"],
     "blurb": "Jazz-soaked balconies, Creole kitchens and Mardi Gras color.",
     "image_query": "new orleans french quarter"},
    {"name": "Banff & the Rockies", "country": "Canada", "region": "Canada West", "continent": "North America",
     "best_months": [6, 7, 8, 9], "daily_cost_usd": 150, "flight_band": 2,
     "tags": ["mountains", "nature", "adventure", "hiking", "road trip"],
     "blurb": "Glacier-fed turquoise lakes beneath the soaring Canadian Rockies.",
     "image_query": "banff lake louise mountains"},
    {"name": "Vancouver", "country": "Canada", "region": "Canada West", "continent": "North America",
     "best_months": [6, 7, 8, 9], "daily_cost_usd": 140, "flight_band": 2,
     "tags": ["city", "nature", "food", "family"],
     "blurb": "Sea-to-sky city with rainforest parks and mountain ski lifts.",
     "image_query": "vancouver skyline mountains"},
    {"name": "Quebec City", "country": "Canada", "region": "Canada East", "continent": "North America",
     "best_months": [6, 7, 8, 9, 12], "daily_cost_usd": 120, "flight_band": 2,
     "tags": ["history", "romance", "culture", "winter"],
     "blurb": "A walled French-colonial old town, magical under winter snow.",
     "image_query": "quebec city chateau frontenac"},
    {"name": "Mexico City", "country": "Mexico", "region": "Mexico", "continent": "North America",
     "best_months": [3, 4, 5, 10, 11], "daily_cost_usd": 60, "flight_band": 2,
     "tags": ["food", "culture", "history", "art", "budget", "city"],
     "blurb": "Aztec ruins, world-ranked restaurants and mural-splashed plazas.",
     "image_query": "mexico city zocalo"},
    {"name": "Cancun & Riviera Maya", "country": "Mexico", "region": "Mexico", "continent": "North America",
     "best_months": [11, 12, 1, 2, 3, 4], "daily_cost_usd": 110, "flight_band": 2,
     "tags": ["beach", "family", "nightlife", "diving", "history", "all-inclusive"],
     "blurb": "Caribbean sand, cenote swims and Maya pyramids inland.",
     "image_query": "cancun riviera maya beach"},
    {"name": "Oaxaca", "country": "Mexico", "region": "Mexico", "continent": "North America",
     "best_months": [10, 11, 3, 4], "daily_cost_usd": 50, "flight_band": 2,
     "tags": ["food", "culture", "history", "budget", "art"],
     "blurb": "Mezcal, mole and Day-of-the-Dead color in a colonial-craft town.",
     "image_query": "oaxaca mexico colorful street"},
    {"name": "Havana", "country": "Cuba", "region": "Caribbean", "continent": "North America",
     "best_months": [12, 1, 2, 3, 4], "daily_cost_usd": 70, "flight_band": 2,
     "tags": ["culture", "history", "music", "beach", "vintage"],
     "blurb": "Classic cars, salsa courtyards and crumbling colonial grandeur.",
     "image_query": "havana cuba classic car"},
    {"name": "Costa Rica (Arenal & Manuel Antonio)", "country": "Costa Rica", "region": "Central America", "continent": "North America",
     "best_months": [12, 1, 2, 3, 4], "daily_cost_usd": 90, "flight_band": 3,
     "tags": ["nature", "adventure", "wildlife", "beach", "eco"],
     "blurb": "Volcano hot springs, cloud forests and zip-line jungle thrills.",
     "image_query": "costa rica arenal volcano rainforest"},

    # ---------------------- SOUTH AMERICA ----------------------
    {"name": "Rio de Janeiro", "country": "Brazil", "region": "Brazil", "continent": "South America",
     "best_months": [12, 1, 2, 3], "daily_cost_usd": 80, "flight_band": 4,
     "tags": ["beach", "nightlife", "nature", "city", "culture"],
     "blurb": "Christ the Redeemer over samba beaches and forested peaks.",
     "image_query": "rio de janeiro christ redeemer"},
    {"name": "Machu Picchu & Cusco", "country": "Peru", "region": "Andes", "continent": "South America",
     "best_months": [5, 6, 7, 8, 9], "daily_cost_usd": 75, "flight_band": 4,
     "tags": ["history", "adventure", "hiking", "culture", "nature"],
     "blurb": "The cloud-wrapped Inca citadel above the Sacred Valley.",
     "image_query": "machu picchu peru"},
    {"name": "Buenos Aires", "country": "Argentina", "region": "Southern Cone", "continent": "South America",
     "best_months": [3, 4, 10, 11], "daily_cost_usd": 60, "flight_band": 4,
     "tags": ["city", "food", "nightlife", "culture", "tango", "budget"],
     "blurb": "Tango cafes, steakhouse nights and grand European boulevards.",
     "image_query": "buenos aires colorful street"},
    {"name": "Patagonia (Torres del Paine)", "country": "Chile", "region": "Patagonia", "continent": "South America",
     "best_months": [11, 12, 1, 2, 3], "daily_cost_usd": 140, "flight_band": 4,
     "tags": ["nature", "adventure", "hiking", "mountains", "wildlife"],
     "blurb": "Granite spires, glaciers and wind-swept trekking at the world's end.",
     "image_query": "torres del paine patagonia"},
    {"name": "Cartagena", "country": "Colombia", "region": "Caribbean Coast", "continent": "South America",
     "best_months": [12, 1, 2, 3], "daily_cost_usd": 65, "flight_band": 3,
     "tags": ["beach", "history", "romance", "nightlife", "culture"],
     "blurb": "A walled Caribbean old town of bougainvillea balconies and salsa nights.",
     "image_query": "cartagena colombia old town"},
    {"name": "Galapagos Islands", "country": "Ecuador", "region": "Pacific", "continent": "South America",
     "best_months": [6, 7, 8, 12, 1], "daily_cost_usd": 280, "flight_band": 4,
     "tags": ["wildlife", "nature", "adventure", "diving", "luxury"],
     "blurb": "Fearless tortoises, blue-footed boobies and snorkel-with-sea-lions wonder.",
     "image_query": "galapagos tortoise sea lion"},

    # ---------------------- OCEANIA ----------------------
    {"name": "Sydney", "country": "Australia", "region": "Australia East", "continent": "Oceania",
     "best_months": [10, 11, 12, 3, 4], "daily_cost_usd": 150, "flight_band": 4,
     "tags": ["city", "beach", "food", "family", "nature"],
     "blurb": "Harbour icons, surf beaches and a laid-back outdoor lifestyle.",
     "image_query": "sydney opera house harbour"},
    {"name": "Great Barrier Reef (Cairns)", "country": "Australia", "region": "Australia East", "continent": "Oceania",
     "best_months": [6, 7, 8, 9, 10], "daily_cost_usd": 160, "flight_band": 4,
     "tags": ["beach", "diving", "nature", "adventure", "family"],
     "blurb": "The world's largest reef, a riot of coral and tropical fish.",
     "image_query": "great barrier reef coral"},
    {"name": "Melbourne", "country": "Australia", "region": "Australia South", "continent": "Oceania",
     "best_months": [3, 4, 11, 12], "daily_cost_usd": 140, "flight_band": 4,
     "tags": ["city", "food", "art", "culture", "coffee"],
     "blurb": "Laneway coffee, street art and a famously good-eating culture.",
     "image_query": "melbourne laneway street art"},
    {"name": "Queenstown", "country": "New Zealand", "region": "South Island", "continent": "Oceania",
     "best_months": [12, 1, 2, 3, 6, 7, 8], "daily_cost_usd": 150, "flight_band": 4,
     "tags": ["adventure", "mountains", "nature", "skiing", "bungee"],
     "blurb": "The adventure capital: bungee, jet boats and Lord-of-the-Rings peaks.",
     "image_query": "queenstown new zealand lake mountains"},
    {"name": "Fiji", "country": "Fiji", "region": "Pacific", "continent": "Oceania",
     "best_months": [5, 6, 7, 8, 9, 10], "daily_cost_usd": 160, "flight_band": 4,
     "tags": ["beach", "luxury", "romance", "honeymoon", "diving", "family"],
     "blurb": "Soft-coral diving, island resorts and famously warm welcomes.",
     "image_query": "fiji island beach"},
    {"name": "Bora Bora", "country": "French Polynesia", "region": "Pacific", "continent": "Oceania",
     "best_months": [5, 6, 7, 8, 9, 10], "daily_cost_usd": 400, "flight_band": 4,
     "tags": ["beach", "luxury", "romance", "honeymoon", "diving"],
     "blurb": "The ultimate overwater-bungalow lagoon beneath a volcanic peak.",
     "image_query": "bora bora overwater bungalow"},
    {"name": "Auckland & Bay of Islands", "country": "New Zealand", "region": "North Island", "continent": "Oceania",
     "best_months": [12, 1, 2, 3], "daily_cost_usd": 130, "flight_band": 4,
     "tags": ["nature", "beach", "city", "adventure", "family"],
     "blurb": "Sailing harbours, volcanic islands and subtropical bays.",
     "image_query": "bay of islands new zealand"},

    # ---------------------- MORE ASIA ----------------------
    {"name": "Osaka", "country": "Japan", "region": "East Asia", "continent": "Asia",
     "best_months": [3, 4, 10, 11], "daily_cost_usd": 110, "flight_band": 4,
     "tags": ["food", "city", "nightlife", "family", "culture"],
     "blurb": "Japan's kitchen: street-food arcades, neon canals and a hilltop castle.",
     "image_query": "osaka dotonbori night"},
    {"name": "Ubud", "country": "Indonesia", "region": "Southeast Asia", "continent": "Asia",
     "best_months": [4, 5, 6, 7, 8, 9], "daily_cost_usd": 40, "flight_band": 3,
     "tags": ["wellness", "nature", "culture", "romance", "budget", "yoga"],
     "blurb": "Bali's spiritual heart of jungle yoga retreats and rice-paddy walks.",
     "image_query": "ubud bali jungle"},
    {"name": "Hoi An", "country": "Vietnam", "region": "Southeast Asia", "continent": "Asia",
     "best_months": [2, 3, 4, 7, 8], "daily_cost_usd": 35, "flight_band": 3,
     "tags": ["culture", "romance", "food", "budget", "history"],
     "blurb": "Lantern-lit riverside old town of tailors, temples and beach bikes.",
     "image_query": "hoi an lanterns river"},
    {"name": "Boracay", "country": "Philippines", "region": "Southeast Asia", "continent": "Asia",
     "best_months": [11, 12, 1, 2, 3, 4], "daily_cost_usd": 55, "flight_band": 3,
     "tags": ["beach", "nightlife", "water sports", "relaxation"],
     "blurb": "Powder-white sand and sunset sailing on a compact island.",
     "image_query": "boracay white beach"},
    {"name": "Palawan", "country": "Philippines", "region": "Southeast Asia", "continent": "Asia",
     "best_months": [11, 12, 1, 2, 3, 4], "daily_cost_usd": 50, "flight_band": 3,
     "tags": ["beach", "nature", "diving", "adventure", "island hopping"],
     "blurb": "Hidden lagoons and limestone cliffs on the world's island-hopping dream.",
     "image_query": "palawan el nido lagoon"},
    {"name": "Bagan", "country": "Myanmar", "region": "Southeast Asia", "continent": "Asia",
     "best_months": [11, 12, 1, 2], "daily_cost_usd": 35, "flight_band": 3,
     "tags": ["history", "culture", "budget", "photography"],
     "blurb": "Thousands of ancient temples on a plain best seen by balloon at dawn.",
     "image_query": "bagan temples balloon"},
    {"name": "Tbilisi", "country": "Georgia", "region": "Caucasus", "continent": "Asia",
     "best_months": [5, 6, 9, 10], "daily_cost_usd": 40, "flight_band": 2,
     "tags": ["culture", "food", "wine", "budget", "history", "city"],
     "blurb": "Sulfur baths, cliff-top churches and a buzzing natural-wine scene.",
     "image_query": "tbilisi old town georgia"},

    # ---------------------- MORE EUROPE ----------------------
    {"name": "Milan & the Lakes", "country": "Italy", "region": "Southern Europe", "continent": "Europe",
     "best_months": [5, 6, 9, 10], "daily_cost_usd": 135, "flight_band": 2,
     "tags": ["city", "luxury", "shopping", "romance", "art"],
     "blurb": "Fashion-capital style with Lake Como villas an hour away.",
     "image_query": "lake como italy"},
    {"name": "Andalusia (Granada)", "country": "Spain", "region": "Southern Europe", "continent": "Europe",
     "best_months": [4, 5, 9, 10], "daily_cost_usd": 80, "flight_band": 2,
     "tags": ["history", "culture", "romance", "food"],
     "blurb": "The Alhambra's Moorish palaces above whitewashed Sierra-Nevada streets.",
     "image_query": "alhambra granada spain"},
    {"name": "Bruges", "country": "Belgium", "region": "Western Europe", "continent": "Europe",
     "best_months": [4, 5, 6, 9, 12], "daily_cost_usd": 110, "flight_band": 2,
     "tags": ["romance", "history", "culture", "chocolate"],
     "blurb": "A canal-laced medieval fairytale of belfries, chocolate and beer.",
     "image_query": "bruges canal belgium"},
    {"name": "Scottish Highlands", "country": "United Kingdom", "region": "Western Europe", "continent": "Europe",
     "best_months": [5, 6, 7, 8, 9], "daily_cost_usd": 130, "flight_band": 2,
     "tags": ["nature", "road trip", "adventure", "mountains", "history"],
     "blurb": "Brooding glens, lochs and castles along the wild Isle of Skye road.",
     "image_query": "scottish highlands skye"},
    {"name": "Faroe Islands", "country": "Denmark", "region": "Northern Europe", "continent": "Europe",
     "best_months": [6, 7, 8], "daily_cost_usd": 160, "flight_band": 2,
     "tags": ["nature", "adventure", "hiking", "photography", "road trip"],
     "blurb": "Sheer green cliffs, turf-roofed villages and dramatic North-Atlantic light.",
     "image_query": "faroe islands cliffs"},

    # ---------------------- MORE AMERICAS ----------------------
    {"name": "Yellowstone & Grand Teton", "country": "United States", "region": "USA West", "continent": "North America",
     "best_months": [6, 7, 8, 9], "daily_cost_usd": 130, "flight_band": 2,
     "tags": ["nature", "wildlife", "adventure", "road trip", "family", "hiking"],
     "blurb": "Geysers, bison herds and jagged peaks across America's first park.",
     "image_query": "yellowstone geyser bison"},
    {"name": "Tulum", "country": "Mexico", "region": "Mexico", "continent": "North America",
     "best_months": [11, 12, 1, 2, 3], "daily_cost_usd": 95, "flight_band": 2,
     "tags": ["beach", "wellness", "romance", "history", "nightlife"],
     "blurb": "Boho beach clubs, cenote dips and clifftop Maya ruins.",
     "image_query": "tulum beach ruins"},
    {"name": "Medellin", "country": "Colombia", "region": "Andes", "continent": "South America",
     "best_months": [1, 2, 3, 7, 8, 12], "daily_cost_usd": 50, "flight_band": 3,
     "tags": ["city", "nightlife", "culture", "budget", "food"],
     "blurb": "The eternal-spring city of cable cars, street art and rooftop salsa.",
     "image_query": "medellin colombia comuna"},
    {"name": "Iguazu Falls", "country": "Argentina", "region": "Northeast", "continent": "South America",
     "best_months": [3, 4, 5, 9, 10], "daily_cost_usd": 80, "flight_band": 4,
     "tags": ["nature", "adventure", "wildlife", "family"],
     "blurb": "A thundering chain of 275 jungle waterfalls on the Brazil-Argentina line.",
     "image_query": "iguazu falls"},
    {"name": "Atacama Desert", "country": "Chile", "region": "North", "continent": "South America",
     "best_months": [4, 5, 9, 10, 11], "daily_cost_usd": 110, "flight_band": 4,
     "tags": ["nature", "adventure", "stargazing", "road trip"],
     "blurb": "The world's driest desert: salt flats, geysers and the clearest night skies.",
     "image_query": "atacama desert chile stars"},

    # ---------------------- INDIA (budget & student favourites) ----------------------
    {"name": "Delhi", "country": "India", "region": "North India", "continent": "Asia",
     "best_months": [10, 11, 2, 3], "daily_cost_usd": 30, "flight_band": 0,
     "tags": ["city", "history", "food", "budget", "culture", "shopping"],
     "blurb": "Mughal forts, chaotic bazaars and India's best street food, all on the metro.",
     "image_query": "delhi india gate red fort"},
    {"name": "Mumbai", "country": "India", "region": "West India", "continent": "Asia",
     "best_months": [11, 12, 1, 2], "daily_cost_usd": 40, "flight_band": 0,
     "tags": ["city", "food", "nightlife", "culture", "history"],
     "blurb": "Colonial seafronts, Bollywood buzz and vada-pav energy that never sleeps.",
     "image_query": "mumbai gateway of india marine drive"},
    {"name": "Amritsar", "country": "India", "region": "North India", "continent": "Asia",
     "best_months": [10, 11, 12, 2, 3], "daily_cost_usd": 22, "flight_band": 0,
     "tags": ["spiritual", "history", "food", "budget", "culture"],
     "blurb": "The Golden Temple's glow, langar meals and the border-ceremony spectacle.",
     "image_query": "amritsar golden temple"},
    {"name": "McLeod Ganj (Dharamshala)", "country": "India", "region": "Himachal Pradesh", "continent": "Asia",
     "best_months": [3, 4, 5, 6, 9, 10], "daily_cost_usd": 20, "flight_band": 0,
     "tags": ["spiritual", "mountains", "budget", "trekking", "nature", "wellness"],
     "blurb": "The Dalai Lama's hillside home of prayer flags, cafes and Triund treks.",
     "image_query": "mcleod ganj dharamshala mountains"},
    {"name": "Kasol & Parvati Valley", "country": "India", "region": "Himachal Pradesh", "continent": "Asia",
     "best_months": [4, 5, 6, 9, 10], "daily_cost_usd": 18, "flight_band": 0,
     "tags": ["nature", "budget", "trekking", "adventure", "mountains"],
     "blurb": "A backpacker riverside base for Kheerganga hikes and Israeli-cafe chill.",
     "image_query": "kasol parvati valley himachal river"},
    {"name": "Spiti Valley", "country": "India", "region": "Himachal Pradesh", "continent": "Asia",
     "best_months": [6, 7, 8, 9], "daily_cost_usd": 25, "flight_band": 0,
     "tags": ["adventure", "mountains", "road trip", "photography", "nature", "budget"],
     "blurb": "A high, stark cold desert of cliff-top monasteries and the world's highest villages.",
     "image_query": "spiti valley key monastery"},
    {"name": "Gokarna", "country": "India", "region": "Karnataka", "continent": "Asia",
     "best_months": [11, 12, 1, 2], "daily_cost_usd": 20, "flight_band": 0,
     "tags": ["beach", "budget", "relaxation", "spiritual"],
     "blurb": "Goa's laid-back little cousin: temple town beaches and cliff-walk coves.",
     "image_query": "gokarna beach karnataka"},
    {"name": "Coorg (Kodagu)", "country": "India", "region": "Karnataka", "continent": "Asia",
     "best_months": [10, 11, 12, 1, 2], "daily_cost_usd": 28, "flight_band": 0,
     "tags": ["coffee", "nature", "budget", "wellness", "wildlife"],
     "blurb": "Misty coffee hills, homestay hospitality and waterfall-and-plantation walks.",
     "image_query": "coorg coffee plantation hills"},
    {"name": "Meghalaya (Shillong & Cherrapunji)", "country": "India", "region": "Northeast India", "continent": "Asia",
     "best_months": [10, 11, 3, 4], "daily_cost_usd": 25, "flight_band": 0,
     "tags": ["nature", "adventure", "trekking", "photography", "budget"],
     "blurb": "Living-root bridges, crystal rivers and the wettest, greenest hills in India.",
     "image_query": "meghalaya living root bridge waterfall"},
    {"name": "Gangtok & Sikkim", "country": "India", "region": "Northeast India", "continent": "Asia",
     "best_months": [3, 4, 5, 10, 11], "daily_cost_usd": 28, "flight_band": 0,
     "tags": ["mountains", "nature", "culture", "adventure", "spiritual"],
     "blurb": "Kanchenjunga views, hilltop monasteries and clean, calm Himalayan towns.",
     "image_query": "gangtok sikkim mountains monastery"},
    {"name": "Rann of Kutch", "country": "India", "region": "Gujarat", "continent": "Asia",
     "best_months": [11, 12, 1, 2], "daily_cost_usd": 30, "flight_band": 0,
     "tags": ["desert", "culture", "photography", "budget"],
     "blurb": "A shimmering white salt desert that hosts the moonlit Rann Utsav craft fair.",
     "image_query": "rann of kutch white desert"},
    {"name": "Varkala", "country": "India", "region": "Kerala", "continent": "Asia",
     "best_months": [11, 12, 1, 2], "daily_cost_usd": 25, "flight_band": 0,
     "tags": ["beach", "wellness", "budget", "yoga", "relaxation"],
     "blurb": "A dramatic red-cliff beach lined with yoga shalas and sunset seafood shacks.",
     "image_query": "varkala cliff beach kerala"},

    # ---------------------- NEIGHBOURS & NEARBY (easy from India) ----------------------
    {"name": "Everest Base Camp Trek", "country": "Nepal", "region": "Himalaya", "continent": "Asia",
     "best_months": [3, 4, 5, 10, 11], "daily_cost_usd": 40, "flight_band": 1,
     "tags": ["trekking", "adventure", "mountains", "nature"],
     "blurb": "The classic two-week Himalayan pilgrimage to the foot of the world's highest peak.",
     "image_query": "everest base camp trek nepal"},
    {"name": "Bhutan (Thimphu & Paro)", "country": "Bhutan", "region": "Himalaya", "continent": "Asia",
     "best_months": [3, 4, 5, 9, 10, 11], "daily_cost_usd": 90, "flight_band": 1,
     "tags": ["culture", "mountains", "spiritual", "nature", "trekking"],
     "blurb": "Cliff-clinging Tiger's Nest, dzong fortresses and a gross-national-happiness calm.",
     "image_query": "bhutan tigers nest paro"},
    {"name": "Ella & Kandy (Sri Lanka)", "country": "Sri Lanka", "region": "Hill Country", "continent": "Asia",
     "best_months": [12, 1, 2, 3, 7, 8], "daily_cost_usd": 35, "flight_band": 2,
     "tags": ["nature", "budget", "trekking", "culture", "wildlife"],
     "blurb": "Tea-terraced hills, the famous train ride and the Temple of the Tooth.",
     "image_query": "ella sri lanka nine arch bridge train"},

    # ---------------------- MORE SOUTHEAST & CENTRAL ASIA (budget) ----------------------
    {"name": "Luang Prabang", "country": "Laos", "region": "Southeast Asia", "continent": "Asia",
     "best_months": [11, 12, 1, 2], "daily_cost_usd": 35, "flight_band": 3,
     "tags": ["culture", "history", "budget", "nature", "food"],
     "blurb": "A serene Mekong temple town of dawn alms, waterfalls and French-Lao cafes.",
     "image_query": "luang prabang laos temple waterfall"},
    {"name": "Krabi & Railay", "country": "Thailand", "region": "Southeast Asia", "continent": "Asia",
     "best_months": [11, 12, 1, 2, 3], "daily_cost_usd": 45, "flight_band": 3,
     "tags": ["beach", "adventure", "budget", "water sports"],
     "blurb": "Limestone karsts, rock-climbing beaches and longtail island-hopping.",
     "image_query": "krabi railay beach thailand"},
    {"name": "Ho Chi Minh City", "country": "Vietnam", "region": "Southeast Asia", "continent": "Asia",
     "best_months": [12, 1, 2, 3], "daily_cost_usd": 30, "flight_band": 3,
     "tags": ["city", "food", "history", "budget", "nightlife"],
     "blurb": "Motorbike swarms, war-history museums and legendary banh-mi and coffee.",
     "image_query": "ho chi minh city vietnam street"},
    {"name": "Pai", "country": "Thailand", "region": "Southeast Asia", "continent": "Asia",
     "best_months": [11, 12, 1, 2], "daily_cost_usd": 28, "flight_band": 3,
     "tags": ["nature", "budget", "relaxation", "adventure"],
     "blurb": "A hippie mountain valley of hot springs, canyons and scooter-loop bliss.",
     "image_query": "pai thailand canyon valley"},
    {"name": "Almaty", "country": "Kazakhstan", "region": "Central Asia", "continent": "Asia",
     "best_months": [5, 6, 9, 10], "daily_cost_usd": 45, "flight_band": 2,
     "tags": ["nature", "mountains", "budget", "adventure", "city"],
     "blurb": "Snow-peak backdrops, alpine lakes and a leafy, café-filled Soviet-era city.",
     "image_query": "almaty kazakhstan mountains kolsai lake"},
    {"name": "Baku", "country": "Azerbaijan", "region": "Caucasus", "continent": "Asia",
     "best_months": [4, 5, 6, 9, 10], "daily_cost_usd": 45, "flight_band": 2,
     "tags": ["city", "culture", "budget", "history"],
     "blurb": "Flame-Tower skyline over a walled old city, with mud volcanoes nearby.",
     "image_query": "baku azerbaijan flame towers old city"},
]


def _build() -> List[Dict]:
    out = []
    for i, d in enumerate(_RAW):
        d = dict(d)
        d["id"] = i + 1
        d["budget_tier"] = _tier(d["daily_cost_usd"])
        out.append(d)
    return out


DESTINATIONS: List[Dict] = _build()


# A flat set of every interest tag we know about (handy for prompting / UI).
ALL_TAGS = sorted({t for d in DESTINATIONS for t in d["tags"]})

if __name__ == "__main__":
    print(f"{len(DESTINATIONS)} destinations across "
          f"{len({d['continent'] for d in DESTINATIONS})} continents and "
          f"{len({d['country'] for d in DESTINATIONS})} countries.")
    print("Tags:", ", ".join(ALL_TAGS))
