"""
One-time (resumable) enrichment of the destination dataset with the Groq LLM.

For every destination in destinations.py it asks the model for deep,
itinerary-style detail and writes it to destinations_rich.json, keyed by
destination name.

Usage (from backend/, with GROQ_API_KEY in .env):
    python enrich.py                # enrich everything still missing
    python enrich.py --only India   # only destinations whose country == India
    python enrich.py --force        # regenerate even already-done entries
    python enrich.py --stale        # regenerate entries missing the new fields

It writes after every destination, so it is safe to stop and re-run — already
generated entries are skipped (unless --force / --stale).
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time

from dotenv import load_dotenv

load_dotenv()

from langchain_core.messages import HumanMessage, SystemMessage  # noqa: E402

from agent import _make_llm, _safe_json, SMART_MODEL, MONTH_NAMES  # noqa: E402
from destinations import DESTINATIONS  # noqa: E402

OUT_PATH = os.path.join(os.path.dirname(__file__), "destinations_rich.json")

# Fields that mark an entry as generated with the current (deep) schema. Entries
# missing these are considered "stale" and regenerated by --stale.
REQUIRED_KEYS = ("visa", "safety", "stay_areas", "budget_split", "getting_there")

_SYSTEM = """You are a meticulous, well-travelled editor writing structured trip
data for a premium travel app aimed at INDIAN travellers — students, budget
backpackers and families departing from India. Given a destination, reply with
ONLY a JSON object matching this schema EXACTLY (no prose, no markdown fences):

{
  "tagline": string,                 // one vivid 6-12 word hook, specific to this place
  "ideal_days_min": number,          // realistic minimum trip length in days
  "ideal_days_max": number,          // comfortable maximum in days
  "highlights": string[],            // 6 short, SPECIFIC phrases on what makes it special (name real things)
  "must_visit": [                    // 6 specific, real places/experiences
    {
      "name": string,                // the real place name
      "desc": string,                // one short sentence: what it is
      "why": string                  // one short sentence: why it's worth it / best time of day to go
    }
  ],
  "hidden_gems": string[],           // 3 lesser-known spots or experiences locals rate (real, specific)
  "covers": string[],                // 3-4 nearby areas/towns a trip here can fold in
  "food": string[],                  // 5 iconic dishes/food experiences, each "Dish — one specific detail"
  "stay_areas": [                    // 3 real neighbourhoods/areas to base yourself in
    {
      "name": string,                // the neighbourhood/area name
      "vibe": string                 // who it suits + rough price level (e.g. "backpacker hostels, cheapest", "leafy & mid-range")
    }
  ],
  "budget_split": {                  // how a typical MID day's on-ground spend splits (percentages that add to ~100)
    "stay": string,                  // e.g. "40%"
    "food": string,                  // e.g. "25%"
    "transport": string,             // e.g. "15%"
    "activities": string             // e.g. "20%"
  },
  "getting_there": string,           // one/two sentences: how an Indian traveller gets here from India (typical gateway airports/routes; for Indian destinations, the nearest airport/rail hub and how to reach)
  "getting_around": string,          // one sentence on local transport once there
  "visa": string,                    // for an INDIAN passport: e.g. "Visa-free", "Visa on arrival (~$35)", "e-Visa needed", or "Domestic — no visa" for Indian destinations. Be specific and honest.
  "safety": string,                  // one honest sentence: how safe it is + the main thing to watch (petty theft, scams, solo-female notes, altitude, etc.)
  "sim_connectivity": string,        // one sentence: getting a SIM/eSIM & how good wifi/data is
  "language": string,                // main language(s) + 2 handy phrases with meaning (e.g. "Thai; 'Sawasdee' = hello, 'Khop khun' = thanks. English widely used in tourist areas.")
  "events": [                        // 2-3 notable festivals/events worth timing a trip around
    {"name": string, "when": string} // when = month(s) or season
  ],
  "best_for": string[],              // subset of: couples, families, solo, friends, adventurers, luxury, backpackers, students
  "tips": string[]                   // 5 CONCRETE, place-specific tips (money-saving, timing, what to skip, a common scam). NO generic filler like "book in advance" or "stay hydrated".
}

Rules:
- Use real, well-known, CORRECT place names — never invent landmarks.
- Be specific to THIS destination. Every tip and highlight must be something a
  guidebook for THIS place would say, not generic travel advice.
- Write for a cost-conscious Indian traveller: mention rupee-relevant savings,
  the cheap way to do things, and honest visa/safety facts for an Indian passport.
- Keep every string tight and scannable. Output valid JSON only."""


def _prompt_for(d: dict) -> str:
    months = ", ".join(MONTH_NAMES[m] for m in d["best_months"])
    return (
        f"Destination: {d['name']}, {d['country']} ({d['continent']}).\n"
        f"Vibe: {d['blurb']}\n"
        f"Themes: {', '.join(d['tags'])}.\n"
        f"Best months: {months}.\n"
        f"Typical on-ground spend: about ${d['daily_cost_usd']}/day.\n"
        f"Write the deep JSON trip data for this destination now."
    )


def _load_existing() -> dict:
    try:
        with open(OUT_PATH, "r", encoding="utf-8") as fh:
            return json.load(fh)
    except (FileNotFoundError, json.JSONDecodeError):
        return {}


def _save(data: dict) -> None:
    with open(OUT_PATH, "w", encoding="utf-8") as fh:
        json.dump(data, fh, ensure_ascii=False, indent=2)


def _is_stale(entry: dict) -> bool:
    """True when an entry lacks the current deep-schema fields."""
    return not all(entry.get(k) for k in REQUIRED_KEYS)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", help="restrict to a country (e.g. India)")
    ap.add_argument("--force", action="store_true", help="regenerate every entry")
    ap.add_argument("--stale", action="store_true",
                    help="regenerate entries missing the new deep-schema fields")
    ap.add_argument("--limit", type=int, default=0, help="cap how many to generate this run")
    args = ap.parse_args()

    if not (os.getenv("GROQ_API_KEY") or "").strip():
        sys.exit("GROQ_API_KEY missing — add it to backend/.env first.")

    out = _load_existing()
    llm = _make_llm(SMART_MODEL, temperature=0.5, json_mode=True)

    targets = [d for d in DESTINATIONS if not args.only or d["country"] == args.only]

    def needs(d: dict) -> bool:
        if args.force:
            return True
        entry = out.get(d["name"])
        if entry is None:
            return True
        if args.stale and _is_stale(entry):
            return True
        return False

    todo = [d for d in targets if needs(d)]
    # Fill entirely-missing destinations before re-polishing shallow ones, so a
    # run that gets cut short by the daily token cap still covers the gaps first.
    todo.sort(key=lambda d: 0 if d["name"] not in out else 1)
    if args.limit:
        todo = todo[: args.limit]

    n_missing = sum(1 for d in todo if d["name"] not in out)
    print(f"{len(out)} already stored | {len(todo)} to generate "
          f"({n_missing} missing first, then {len(todo) - n_missing} shallow) "
          f"({'all' if not args.only else args.only}).")

    for i, d in enumerate(todo, 1):
        name = d["name"]
        try:
            resp = llm.invoke([
                SystemMessage(content=_SYSTEM),
                HumanMessage(content=_prompt_for(d)),
            ])
            data = _safe_json(resp.content)
            if not data.get("tagline"):
                raise ValueError("empty/invalid JSON (no tagline)")
            out[name] = data
            _save(out)
            # Note when a field or two is still missing — --stale will re-catch it
            # later rather than us discarding a mostly-good (token-costly) result.
            gaps = [k for k in REQUIRED_KEYS if not data.get(k)]
            note = f" (partial, missing: {', '.join(gaps)})" if gaps else ""
            print(f"  [{i}/{len(todo)}] ok: {name}{note}")
        except Exception as exc:
            print(f"  [{i}/{len(todo)}] FAILED {name}: {exc} (will retry next run)")
            time.sleep(2)  # back off briefly on errors / rate limits

    print(f"Done. {len(out)} destinations enriched -> {OUT_PATH}")


if __name__ == "__main__":
    main()
